name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "75.0"

      - name: Before Install
        run: |
          firefox --version
          make deps
          make venv
          . venv/bin/activate
          export PATH=`npm bin`:$PATH
          make pythondeps
          python -c "import setuptools; print(setuptools.__version__)"
          pip --version

      - name: Install
        run: |
          . venv/bin/activate
          make install

      - name: Before Test
        run: |
          . venv/bin/activate
          make devdeps

      - name: Test
        run: |
          . venv/bin/activate
          flake8 .
          make pythontest
          make jstest
          make docs
          make testimages
          make testdb
          make certs
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
          sleep 3
          pushd jupyterhub
          mkdir -p /tmp/remoteapp
          chmod 755 `pwd`/start.sh
          `pwd`/start.sh &
          popd
          sleep 3
          DISPLAY=:99 python -m unittest discover -s selenium_tests -t . -v

      - name: After Success
        run: |
          pushd jupyterhub
          `pwd`/start.sh &
          popd
          sleep 3
          . venv/bin/activate
          DISPLAY=:99 coverage run -m tornado.testing discover
          pip install codecov
          codecov
          bash <(curl -s https://codecov.io/bash)
