name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        container:
          - 'ubuntu:18.04'
          - 'centos:7'

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Install make on Ubuntu
        if: ${{ matrix.container == 'ubuntu:18.04' }}
        run: sudo apt-get install build-essential

      - name: Install requirements
        run: |
          make deps
          make venv
          . venv/bin/activate
          export PATH=`npm bin`:$PATH
          make pythondeps
          python -c "import setuptools; print(setuptools.__version__)"
          pip --version

      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "75.0"
      - run: firefox --version

      - name: Install Simphony-Remote
        run: |
          . venv/bin/activate
          make install

      - name: Install development requirements
        run: |
          . venv/bin/activate
          make devdeps

      - name: Flake8 checks
        run: |
          . venv/bin/activate
          flake8 .

      - name: Test
        run: |
          . venv/bin/activate
          make pythontest
          make jstest
          make docs
          make testimages
          make testdb
          make certs
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
          sleep 3
          pushd jupyterhub
          mkdir -p /tmp/remoteapp
          chmod 755 `pwd`/start.sh
          `pwd`/start.sh &
          popd
          sleep 3
          DISPLAY=:99 python -m unittest discover -s selenium_tests -t . -v

      - name: Coverage
        run: |
          pushd jupyterhub
          `pwd`/start.sh &
          popd
          sleep 3
          . venv/bin/activate
          DISPLAY=:99 coverage run -m tornado.testing discover
          pip install codecov
          codecov
          bash <(curl -s https://codecov.io/bash)
